### ISSUE TITLE
[BUG] ObjectDetector RuntimeError using WSL 2

### ISSUE THREAD

**Issue by zenetio** [autogluon/autogluon#1624]
I am just running the Object Detection Quick Start motor bike example, using exactly the same source code.
After about 30 seconds, the process stops with the mentioned error.

The expected output should be the complete report showing the best model.

Below is the output I am getting;

<details>

```
/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/gluoncv/__init__.py:40: UserWarning: Both `mxnet==1.9.0` and `torch==1.10.2+cu102` are installed. You might encounter increased GPU memory footprint if both framework are used at the same time.
  warnings.warn(f'Both `mxnet=={mx.__version__}` and `torch=={torch.__version__}` are installed. '
tiny_motorbike/
├── Annotations/
├── ImageSets/
└── JPEGImages/
=============================================================================
WARNING: ObjectDetector is deprecated as of v0.4.0 and may contain various bugs and issues!
In a future release ObjectDetector may be entirely reworked to use Torch as a backend.
This future change will likely be API breaking.Users should ensure they update their code that depends on ObjectDetector when upgrading to future AutoGluon releases.
For more information, refer to ObjectDetector refactor GitHub issue: https://github.com/awslabs/autogluon/issues/1559
=============================================================================

The number of requested GPUs is greater than the number of available GPUs.Reduce the number to 1
Randomly split train_data into train[151]/validation[19] splits.
Starting HPO experiments
  0%|                                                                                                | 0/2 [00:00<?, ?it/s]modified configs(<old> != <new>): {
root.train.wd        0.0005 != 0.0001
root.train.epochs    20 != 5
root.train.early_stop_max_value 1.0 != inf
root.train.seed      233 != 90
root.train.early_stop_patience -1 != 10
root.train.batch_size 16 != 8
root.train.early_stop_baseline 0.0 != -inf
root.dataset_root    ~/.mxnet/datasets/ != auto
root.ssd.base_network vgg16_atrous != resnet50_v1
root.ssd.data_shape  300 != 512
root.gpus            (0, 1, 2, 3) != (0,)
root.valid.batch_size 16 != 8
root.dataset         voc_tiny != auto
}
Saved config to /home/carlos/projects/od_test/747a76d2/.trial_0/config.yaml
Using transfer learning from ssd_512_resnet50_v1_coco, the other network parameters are ignored.
100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.32s/it]
modified configs(<old> != <new>): {
root.train.wd        0.0005 != 0.0001
root.train.epochs    20 != 5
root.train.early_stop_max_value 1.0 != inf
root.train.seed      233 != 90
root.train.early_stop_patience -1 != 10
root.train.batch_size 16 != 8
root.train.early_stop_baseline 0.0 != -inf
root.dataset_root    ~/.mxnet/datasets/ != auto
root.ssd.base_network vgg16_atrous != resnet50_v1
root.ssd.data_shape  300 != 512
root.gpus            (0, 1, 2, 3) != (0,)
root.valid.batch_size 16 != 8
root.dataset         voc_tiny != auto
}
Saved config to /home/carlos/projects/od_test/747a76d2/.trial_0/config.yaml
Using transfer learning from ssd_512_resnet50_v1_coco, the other network parameters are ignored.
Finished, total runtime is 16.90 s
{ 'best_config': { 'dataset': 'auto',
                   'dataset_root': 'auto',
                   'estimator': <class 'gluoncv.auto.estimators.ssd.ssd.SSDEstimator'>,
                   'gpus': [0],
                   'horovod': False,
                   'num_workers': 4,
                   'resume': '',
                   'save_interval': 1,
                   'ssd': { 'amp': False,
                            'base_network': 'resnet50_v1',
                            'data_shape': 512,
                            'filters': None,
                            'nms_thresh': 0.45,
                            'nms_topk': 400,
                            'ratios': ( [1, 2, 0.5],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5],
                                        [1, 2, 0.5]),
                            'sizes': (30, 60, 111, 162, 213, 264, 315),
                            'steps': (8, 16, 32, 64, 100, 300),
                            'syncbn': False,
                            'transfer': 'ssd_512_resnet50_v1_coco'},
                   'train': { 'batch_size': 8,
                              'dali': False,
                              'early_stop_baseline': -inf,
                              'early_stop_max_value': inf,
                              'early_stop_min_delta': 0.001,
                              'early_stop_patience': 10,
                              'epochs': 5,
                              'log_interval': 100,
                              'lr': 0.001,
                              'lr_decay': 0.1,
                              'lr_decay_epoch': (160, 200),
                              'momentum': 0.9,
                              'seed': 90,
                              'start_epoch': 0,
                              'wd': 0.0001},
                   'valid': { 'batch_size': 8,
                              'iou_thresh': 0.5,
                              'metric': 'voc07',
                              'val_interval': 1}},
  'total_time': 16.89547610282898,
  'train_map': -1,
  'valid_map': -1}
Traceback (most recent call last):
  File "/home/carlos/projects/od_test/od_ex1.py", line 16, in <module>
    detector.fit(dataset_train,
  File "/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/autogluon/vision/configs/presets_configs.py", line 18, in _call
    return f(*gargs, **gkwargs)
  File "/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/autogluon/vision/detector/detector.py", line 318, in fit
    self._detector = task.fit(train_data, tuning_data, 1 - holdout_frac, random_state)
  File "/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/autogluon/vision/_gluoncv/object_detection.py", line 365, in fit
    raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}')
RuntimeError: Unexpected error happened during fit: { 'args': "{'ssd': {'base_network': 'resnet50_v1', 'data_shape': 512, "
          "'filters': None, 'sizes': (30, 60, 111, 162, 213, 264, 315), "
          "'ratios': ([1, 2, 0.5], [1, 2, 0.5, 3, 0.3333333333333333], [1, 2, "
          '0.5, 3, 0.3333333333333333], [1, 2, 0.5, 3, 0.3333333333333333], '
          "[1, 2, 0.5], [1, 2, 0.5]), 'steps': (8, 16, 32, 64, 100, 300), "
          "'syncbn': False, 'amp': False, 'transfer': "
          "'ssd_512_resnet50_v1_coco', 'nms_thresh': 0.45, 'nms_topk': 400}, "
          "'train': {'batch_size': 8, 'start_epoch': 0, 'epochs': 5, 'lr': "
          "0.001, 'lr_decay': 0.1, 'lr_decay_epoch': (160, 200), 'momentum': "
          "0.9, 'wd': 0.0001, 'log_interval': 100, 'seed': 90, 'dali': False, "
          "'early_stop_patience': 10, 'early_stop_min_delta': 0.001, "
          "'early_stop_baseline': -inf, 'early_stop_max_value': inf}, 'valid': "
          "{'batch_size': 8, 'val_interval': 1, 'metric': 'voc07', "
          "'iou_thresh': 0.5}, 'dataset': 'auto', 'dataset_root': 'auto', "
          "'gpus': [0], 'resume': '', 'save_interval': 1, 'horovod': False, "
          "'num_workers': 4}",
  'best_config': { 'batch_size': 8,
                   'dist_ip_addrs': None,
                   'early_stop_baseline': -inf,
                   'early_stop_max_value': inf,
                   'early_stop_patience': 10,
                   'epochs': 5,
                   'final_fit': False,
                   'gpus': [0],
                   'lr': 0.001,
                   'momentum': 0.9,
                   'ngpus_per_trial': 8,
                   'nthreads_per_trial': 128,
                   'num_workers': 4,
                   'scheduler': 'local',
                   'seed': 90,
                   'time_limits': 1800,
                   'transfer': 'ssd_512_resnet50_v1_coco',
                   'wd': 0.0001},
  'best_reward': -inf,
  'config_history': OrderedDict(),
  'metadata': { 'resources_per_trial': {'num_cpus': 4, 'num_gpus': 1},
                'search_space': { 'batch_size': 8,
                                  'dist_ip_addrs': None,
                                  'early_stop_baseline': -inf,
                                  'early_stop_max_value': inf,
                                  'early_stop_patience': 10,
                                  'epochs': 5,
                                  'final_fit': False,
                                  'gpus': [0],
                                  'lr': 0.001,
                                  'momentum': 0.9,
                                  'ngpus_per_trial': 8,
                                  'nthreads_per_trial': 128,
                                  'num_workers': 4,
                                  'scheduler': 'local',
                                  'seed': 90,
                                  'time_limits': 1800,
                                  'transfer': Categorical['ssd_512_resnet50_v1_coco', 'yolo3_darknet53_coco', 'faster_rcnn_resnet50_v1b_coco', 'center_net_resnet50_v1b_coco'],
                                  'wd': 0.0001},
                'search_strategy': <autogluon.core.searcher.local_random_searcher.LocalRandomSearcher object at 0x7f08d378cfd0>,
                'stop_criterion': {'max_reward': None, 'time_limits': 1800}},
  'reward_attr': 'map_reward',
  'time': 2.247757911682129,
  'total_time': 16.89547610282898,
  'traceback': 'Traceback (most recent call last):\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/autogluon/vision/_gluoncv/object_detection.py", '
               'line 130, in _train_object_detection\n'
               '    result = estimator.fit(train_data=train_data, '
               'val_data=val_data, time_limit=wall_clock_tick-tic)\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/gluoncv/auto/estimators/base_estimator.py", '
               'line 175, in fit\n'
               '    ret = self._fit(train_data, val_data, '
               'time_limit=time_limit) if not resume else \\\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/gluoncv/auto/estimators/ssd/ssd.py", '
               'line 87, in _fit\n'
               '    return self._resume_fit(train_data, val_data, '
               'time_limit=time_limit)\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/gluoncv/auto/estimators/ssd/ssd.py", '
               'line 112, in _resume_fit\n'
               '    train_loader, val_loader, train_eval_loader = '
               '_get_dataloader(\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/gluoncv/auto/estimators/ssd/utils.py", '
               'line 68, in _get_dataloader\n'
               '    train_loader = gluon.data.DataLoader(\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/mxnet/gluon/data/dataloader.py", '
               'line 654, in __init__\n'
               '    nd.waitall()\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/mxnet/ndarray/ndarray.py", '
               'line 211, in waitall\n'
               '    check_call(_LIB.MXNDArrayWaitAll())\n'
               '  File '
               '"/home/carlos/miniconda3/envs/gluon/lib/python3.9/site-packages/mxnet/base.py", '
               'line 246, in check_call\n'
               '    raise get_last_ffi_error()\n'
               'mxnet.base.MXNetError: Traceback (most recent call last):\n'
               '  File "../src/ndarray/../operator/tensor/./../mxnet_op.h", '
               'line 1120\n'
               'Name: Check failed: err == cudaSuccess (209 vs. 0) : '
               'mxnet_generic_kernel ErrStr:no kernel image is available for '
               'execution on the device\n',
  'train_map': -1,
  'training_history': OrderedDict([(0, []), (1, [])]),
  'valid_map': -1}

```

</details>

I am using a fresh conda env install of autogluon, where I have
autogluon = 0.4.0
mxnet-cu101 = 1.9.0
python = 3.9.7
WSL 2 = 0.56.2.0
Kernel version = 5.10.102.1
Window version = 10.0.22563.1

**Comment by Innixma** [comment]
Thanks for the bug report! Unfortunately, MXNet on Windows (even with WSL) may have various bugs. We are in the process of switching all of our code to use Torch, however ObjectDetector has not yet been migrated as of v0.4. If you can reproduce this error on a Colab notebook, this would help us for reproducibility, but most likely your issue will be naturally fixed after we migrate ObjectDetector to Torch. We currently don't have a timeline for when this will be done, but will notify this thread when it is available.

**Comment by Innixma** [comment]
Probably fixed in v0.7
